/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CountComponent {
        "count": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StateComponent {
    }
}
declare global {
    interface HTMLCountComponentElement extends Components.CountComponent, HTMLStencilElement {
    }
    var HTMLCountComponentElement: {
        prototype: HTMLCountComponentElement;
        new (): HTMLCountComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStateComponentElement extends Components.StateComponent, HTMLStencilElement {
    }
    var HTMLStateComponentElement: {
        prototype: HTMLStateComponentElement;
        new (): HTMLStateComponentElement;
    };
    interface HTMLElementTagNameMap {
        "count-component": HTMLCountComponentElement;
        "my-component": HTMLMyComponentElement;
        "state-component": HTMLStateComponentElement;
    }
}
declare namespace LocalJSX {
    interface CountComponent {
        "count"?: number;
        "onOnCountLimit"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StateComponent {
    }
    interface IntrinsicElements {
        "count-component": CountComponent;
        "my-component": MyComponent;
        "state-component": StateComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "count-component": LocalJSX.CountComponent & JSXBase.HTMLAttributes<HTMLCountComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "state-component": LocalJSX.StateComponent & JSXBase.HTMLAttributes<HTMLStateComponentElement>;
        }
    }
}
